# this is the input to logstash. All input goes through here and selected 
# to go to some other pipeline.
#
#tcp syslog stream via 5140
input {
  tcp {
    type => "syslog"
    port => 5140
  }
}
#udp syslogs stream via 5140
input {
  udp {
    type => "syslog"
    port => 5140
  }
}

## other inputs later will maybee also be added here

output {
  if [type] == "syslog" {
    pipeline { send_to => syslog }
  } else {
    pipeline { send_to => output }
  }
}
