# This is our input for the syslog pipeline.
# it maybee is not syslog

input { pipeline { address => "syslog" } }

## ECS common schema for syslog
#log.syslog
#          .appname
#          .hostname
#          .msgid
#          .priority
#          .procid
#          .version    # only some versions RFC 5424
#          .structured_data  # only some version RFC 5424
#          .severity
#                   .code
#                   .name
#          .facility
#                   .code
#                   .name

# [host]


# the syslog pipeline takes an event string and parses it into
# severity, faclility, timestamp, hostname, process-name process id, and message from process like:
# <INT> 2026-06-06T16:07:00.251403+02:00 hpelitebook sshd-session[20350]: Accepted password for wooflock from ::1 port 33304 ssh2

# Syslog date fields can be very diffrent. so we try and handle that with date.
#  we also add some metadata for this to keep track

filter {
  grok {
    id => "grok_syslog_parse"
    patterns_dir => ["/etc/logstash/patterns/pipes"]
    match => { "message" => "(<%{INT:log_entry}>)?%{SYSLOG_TS:log_timestamp} %{SYSLOGHOST:[log][syslog][hostname]} %{DATA:[log][syslog][appname]}(\[%{POSINT:[log][syslog][procid]}\])?: %{GREEDYDATA:syslog_message}" }
    tag_on_failure => ["_grokfail:pipeline=syslog:filter=grok_syslog_parse"]
  }
  # if the grok above did not work out we catch it here.
  if "_grokfail:pipeline=syslog:filter=grok_syslog_parse" in [tags] {
    mutate {
      add_field => {
        "[logstash][failure][pipeline]" => "syslog"
        "[logstash][failure][filter]" => "grok_syslog_parse"
      }
    }
  }

  syslog_pri { }

  date {
    match => [
      "log_timestamp",
      "dd/MMM/yyyy:HH:mm:ss Z",
      "yyyy-MM-dd HH:mm:ss.SSSS",
      "MMM dd HH:mm:ss",
      "ISO8601"
    ]
    target => "@timestamp"
    # Optional: remove the temporary string field so it doesn't clutter your index
    #remove_field => [ "log_timestamp" ]
  }

  #mutate {
  #  remove_field => [ "log_entry" ]
  #}
  mutate { copy => { "[log][syslog][appname]" => "[process][name]" } }
  mutate { copy => { "[log][syslog][procid]" => "[process][pid]" } }
  mutate { copy => { "[log][syslog][hostname]" => "[host][hostname]" } }
  mutate { copy => { "[log][syslog][hostname]" => "[host][name]" } }


  mutate {
    split => { "[host][name]" => "." }
    add_field => { "tmphostname" => "%{[host][name][0]}" }
  }

  mutate {
    rename => { "tmphostname" => "[host][name]" }
  }
}



output {
  if [log][syslog][appname] == "sshd" {
    pipeline { send_to => ssh }
  }
  else if [log][syslog][appname] == "sshd-session" {
    pipeline { send_to => ssh }
  }
  else if [log][syslog][appname] == "sudo" {
    pipeline { send_to => sudo }
  }
  else if [log][syslog][appname] == "NetworkManager" {
    pipeline { send_to => "linux-networkmanager" }
  }
  else {
    pipeline { send_to => output }
  }
}
