# this is the input to systemd-logind. All input goes through here and selected 
# to go to some other pipeline.

input { pipeline { address => "linux-systemd-logind" } }

# events in ecs that we place here relevant on this level.
# [error][message]
#        [code]
#        [type]
#        [stack_trace]
#        [id]
#
# [event]
#        [action]
#        [category]
#        [code]
#        [created]  # we place @timestamp here
#        [dataset]  
#        [hash] # hash of the log to demonstrate integrity
#        [kind] # alert, asset, enrichment, event, metric, state, pipeline_error, signal
#        [module]
#        [outcome] # failure, success, unknown
#        [reason]
#        [reference] # link to where we find more data.. Misp event link etc.
#        [sequence]
#        [severity] # you can copy log.syslog.severity.code here if not a special one exists
#        [type] # access, admin, allowed, change, connection, creation, deletion, denied, device, end, error, group, indicator (array)
#
# [host]

#    filter {
       # Weblog filter statements here...
#    }

filter {
  grok {
    id => "grok_systemd_logind_parse"
    patterns_dir => ["/etc/logstash/patterns/pipes"]
    match => { "syslog_message" => 
      "%{APP_SYSTEMD_LOGIND}" }
    tag_on_failure => ["_grokfail:pipeline=linux_systemd_logind:filter=grok_systemd_logind_parse"]
  }

  if [syslog_message] =~ /^New session/ {
    mutate {
      add_field => {
        "[event][action]" => "systemd_logind_session_created"
        "[event][outcome]" => "success"
      }
    }
    ruby { # setting array items that work on all logstash versions.
      code => '
        event.set("[event][category]", ["session"])
        event.set("[event][type]", ["start"])
      '
    }
  }
  else if [syslog_message] =~ /^Session .* logged out/ {
    mutate {
      add_field => {
        "[event][action]" => "systemd_logind_session_logged_out"
        "[event][outcome]" => "success"
      }
    }
    ruby { # setting array items that work on all logstash versions.
      code => '
        event.set("[event][category]", ["session"])
        event.set("[event][type]", ["end"])
      '
    }
  }
  else if [syslog_message] =~ /^Removed session / {
    mutate {
      add_field => {
        "[event][action]" => "systemd_logind_session_removed"
        "[event][outcome]" => "success"
      }
    }
    ruby { # setting array items that work on all logstash versions.
      code => '
        event.set("[event][category]", ["session"])
        event.set("[event][type]", ["deletion"])
      '
    }
  }

  

  # add metadata for all events that pass through
  mutate {
    add_field => {
      "[event][module]" => "linux"
      "[event][dataset]" => "linux.systemd_logind"
      "[service][type]" => "systemd-logind"
      "[service][name]" => "systemd-logind"
    }
  }

}

output {
  pipeline { send_to => output }
}
