# this is the input to NetworkManager. All input goes through here and selected 
# to go to some other pipeline.

input { pipeline { address => "linux-networkmanager" } }

# events in ecs that we place here relevant on this level.
# [error][message]
#        [code]
#        [type]
#        [stack_trace]
#        [id]
#
# [event]
#        [action]
#        [category]
#        [code]
#        [created]  # we place @timestamp here
#        [dataset]  
#        [hash] # hash of the log to demonstrate integrity
#        [kind] # alert, asset, enrichment, event, metric, state, pipeline_error, signal
#        [module]
#        [outcome] # failure, success, unknown
#        [reason]
#        [reference] # link to where we find more data.. Misp event link etc.
#        [sequence]
#        [severity] # you can copy log.syslog.severity.code here if not a special one exists
#        [type] # access, admin, allowed, change, connection, creation, deletion, denied, device, end, error, group, indicator (array)
#
# [host]

#    filter {
       # Weblog filter statements here...
#    }

filter {
  grok {
    id => "grok_networkmanager_parse"
    patterns_dir => ["/etc/logstash/patterns/pipes"]
    match => { "syslog_message" => 
      "%{NM_TOTAL}" }
    tag_on_failure => ["_grokfail:pipeline=linux_networkmanager:filter=grok_network_manager_parse"]
  }
  if "_grokfail:pipeline=linux_networkmanager:filter=grok_networkmanager_parse" in [tags] {
    mutate {
      add_field => {
        "[logstash][failure][pipeline]" => "linux-networkmanager"
        "[logstash][failure][filter]" => "grok_networkmanager_parse"
      }
    }
  }
  




}

output {
  pipeline { send_to => output }
}
