# this is the input to logstash. All input goes through here and selected 
# to go to some other pipeline.
#

input { pipeline { address => sudo } }

filter {
  grok {
    id => "grok_sudo_parse"
    patterns_dir => ["/etc/logstash/patterns/pipes"]
    match => { "syslog_message" => "%{APP_SUDO}" }
    tag_on_failure => ["_grokfail:pipeline=sudo:filter=grok_sudo_parse"]
  }

  # we add some meta that always goes with sudo
  mutate {
    add_field => {
      "[event][module]" => "sudo"
      "[event][dataset]" => "sudo.log"
      "[service][type]" => "sudo"
      "[service][name]" => "sudo"
    }
  }

  if [syslog_message] =~ /incorrect password attempts/ {
    mutate {
      add_field => {
        "[event][action]" => "sudo_incorrect_password_attempts"
        "[event][outcome]" => "failure"
      }
    }
    ruby {
      code => '
        event.set("[event][category]", ["authentication"])
        event.set("[event][type]", ["denied", "user"])
      '
    }
  }
  else if [syslog_message] =~ /authentication failure/ {
    mutate {
      add_field => {
        "[event][action]" => "sudo_authentication_failure"
        "[event][outcome]" => "failure"
      }
    }
    ruby {
      code => '
        event.set("[event][category]", ["authentication"])
        event.set("[event][type]", ["denied", "user"])
      '
    }
  }
  else if [syslog_message] =~ /session opened/ {
    mutate {
      add_field => {
        "[event][action]" => "sudo_session_opened"
        "[event][outcome]" => "success"
      }
    }
    ruby {
      code => '
        event.set("[event][category]", ["session"])
        event.set("[event][type]", ["start", "user"])
      '
    }
  }
  else if [syslog_message] =~ /session closed/ {
    mutate {
      add_field => {
        "[event][action]" => "sudo_session_closed"
        "[event][outcome]" => "success"
      }
    }
    ruby {
      code => '
        event.set("[event][category]", ["session"])
        event.set("[event][type]", ["end", "user"])
      '
    }
  }
  else if [process][command_line] {
    mutate {
      add_field => {
        "[event][action]" => "sudo_command"
        "[event][outcome]" => "success"
      }
    }
    ruby {
      code => '
        event.set("[event][category]", ["process"])
        event.set("[event][type]", ["start", "user"])
      '
    }
  }

  # add some cleanup.
  # if source address is empty remove it.
  if [source][address] =~ /^\s*$/ {
    mutate {
      remove_field => [ "[source][address]" ]
    }
  }

}


output
{
  pipeline { send_to => output }
}

