# this is the input to logstash. All input goes through here and selected
# to go to some other pipeline.
#

input { pipeline { address => sudo } }
#    filter {
       # Weblog filter statements here...
#    }
output
{
  pipeline { send_to => output }
}
