# this is the input to logstash. All input goes through here and selected 
# to go to some other pipeline.
#
input { pipeline { address => output } }

#    filter {
       # Weblog filter statements here...
#    }
filter {
  if [log][syslog][appname] == "systemd" {
    drop { }
  }
}

output {
  file {
    path => "/var/log/logstash/testing.json"
    codec => json_lines
  } 
  #stdout { codec => rubydebug }
}

