# this is the input to logstash. All input goes through here and selected 
# to go to some other pipeline.
#
input { pipeline { address => output } }

filter {
  # right now we drop things to not look at them.
  if [log][syslog][appname] == "systemd" {
    drop { }
  }

  # some things that universally apply.
  # if we have a [user][name] we probably also should have a [event][type] ["user","..",".."]
  if [user][name] {
    # we use ruby for this, since this handles array items on all logstash versions.
    ruby {
      code => '
        types = event.get("[event][type]")
        types = [] if types.nil?
        types = [types] unless types.is_a?(Array)
        types << "user" unless types.include?("user")
        event.set("[event][type]", types)
    '
    }
  }


}

output {
  file {
    path => "/var/log/logstash/testing.json"
    codec => json_lines
  } 
  #stdout { codec => rubydebug }
}

